### ISSUE TITLE
Tag Manager を取得する

### ISSUE THREAD

**Issue by aggre** [Polymer-Japan/polymer-jp.org#10]

**Comment by howking** [comment]
@aggre @jtakiguchi とりあえずテストサイトのタグマネージャを[共有](https://tagmanager.google.com/#/container/accounts/1926146881/containers/7747241)しましたので設定を見ていただければです（トリガーはページビューと履歴の変更のみ）

ソース上は[ここ](https://github.com/howking/polymer-jp.org/blob/13e88ed5584758ecc348c24dfbcf980b2d83b57f/src/polymer-jp.html#L111)のIDを修正する想定です。

**Comment by aggre** [comment]
Tag Manager を取得しました。

@howking 本番用のタグマネージャを[共有](https://tagmanager.google.com/#/container/accounts/1932932575/containers/7757539)します。
