### ISSUE TITLE
Analytics を取得する

### ISSUE THREAD

**Issue by aggre** [Polymer-Japan/polymer-jp.org#11]

**Comment by howking** [comment]
@aggre @jtakiguchi #10 と関連して念の為Analyticsも[共有](https://analytics.google.com/analytics/web/#embed/report-home/a3657657w161966701p163003005/)しておきましたので、ご参考までに（現状なんの設定もしていません）。

**Comment by aggre** [comment]
Analytics を取得しました。

@howking 共有ありがとうございます！参考になりました。本番用の Analytics を[共有](https://analytics.google.com/analytics/web/#embed/report-home/a108532417w162155813p163185123/)します。
