### ISSUE TITLE
Firefox Nightly で閲覧できない

### ISSUE THREAD

**Issue by aggre** [Polymer-Japan/polymer-jp.org#21]
# 現象

https://polymer-jp.org を閲覧すると `TypeError: this._meta.byKey is not a function` エラーが発生してヘッダー以外が表示されない。

# 環境

Browser | Browser Version | OS | OS Version
---- | ---- | ---- | ----
Firefox | 59.0a1 (2017-11-20) (64-bit) | Mac | 10.13.1 (17B48)

**Comment by howking** [comment]
Stableでは動いていてそうなので、いったん様子見させてください(また問題が起きたらオープンする感じで)

Browser | Browser Version | OS | OS Version
---- | ---- | ---- | ----
Firefox | 57 (Quantum 64-bit) | Mac | 10.12.6

**Comment by howking** [comment]
念の為Nightlyをインストールして開いてみましたが、再現しませんね、、、
1日経って直ったのかな、OS Versionの違い?

![image](https://user-images.githubusercontent.com/13231263/33111375-09966650-cf91-11e7-9752-899df198cb94.png)

Browser | Browser Version | OS | OS Version
---- | ---- | ---- | ----
Firefox | 59.0a1 (2017-11-21) | Mac | 10.12.6
