### ISSUE TITLE
ページ左上のトップページリンクを文字にも適用

### ISSUE THREAD

**Issue by usagi-f** [Polymer-Japan/polymer-jp.org#24]
![image](https://user-images.githubusercontent.com/9045135/33207471-32fc4840-d151-11e7-8e5a-0ee043839417.png)
![image](https://user-images.githubusercontent.com/9045135/33207474-37b1570e-d151-11e7-955c-f3439b780931.png)

リンクがアイコンにしかなくて、混乱することがあるので「Polymer Japan」というテキスト部分を押下しても遷移するようにする

**Comment by usagi-f** [comment]
よくみたら青背景のときは `Polymer JP` なんですね

これを機に `polymer-jp-title.html` のようなカスタムコンポーネントを作ってみようと思います。

**Comment by howking** [comment]
幅の都合上でしたが、[BETA]とかも適当に置いてるだけなので、自由にいじっていただければです!
