### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by aggre** [Polymer-Japan/polymer-jp.org#6]
Code of Conductのページを追加する

**Comment by aggre** [comment]
CoC: https://docs.google.com/document/d/15iOd0atzcSPWv1nHVl9OJ35Jga_nxNXQU_olwAceAac/edit?usp=sharing

**Comment by howking** [comment]
追加しました。(問題があれば編集していただくか、再オープンしてもらえればです)

https://polymer-jp.org/community/code-of-conduct/
