### ISSUE TITLE
問い合わせ

### ISSUE THREAD

**Issue by aggre** [Polymer-Japan/polymer-jp.org#8]
問い合わせのページを追加する。

Google FormのEmbed→シートの変更通知で受け取る？

**Comment by howking** [comment]
@aggre @jtakiguchi ざっくり問い合わせフォームを作ってみました。
右上のインフォメーションアイコンから送られた内容はいったんFirestoreに[格納](https://console.firebase.google.com/project/polymer-jp-ffc4c/database/firestore/data~2Finquiries)されてから[シート](https://docs.google.com/spreadsheets/d/1x-hd157IdPdAp8_U9JS_VsM3IPAa42kkbw0Hf5fOOuI/edit#gid=0)に保存されるので変更通知がとれるはずです。
