### ISSUE TITLE
Firestore によるコンテンツ管理

### ISSUE THREAD

**Issue by aggre** [Polymer-Japan/polymer-jp.org#9]
Firestore によるコンテンツ管理が可能なバージョンを公開する

**Comment by aggre** [comment]
@howking howking さんが実装されたバージョンを公開したいと考えてます。

事前に Firestore で各コンテンツを整備してからフロントエンドをデプロイする、で問題ないと思っていますが、どうですか？問題のない場合このIssueは閉じます。

**Comment by howking** [comment]
@aggre @jtakiguchi とり急ぎ認証をつけて、テストサイトの[管理画面](https://console.firebase.google.com/project/polymer-jp-ffc4c/overview)を共有しました。
[各ページ](https://polymer-jp-ffc4c.firebaseapp.com/)の右上のGoogleアイコンからログイン、[ユーザ一覧](https://console.firebase.google.com/project/polymer-jp-ffc4c/authentication/users)からUIDをコピーして、Firestoreの[ルール設定](https://console.firebase.google.com/project/polymer-jp-ffc4c/database/firestore/rules)に追加すれば編集できるようになります。

**Comment by howking** [comment]
続いて、新規登録や削除機能もつけましたー。

**Comment by aggre** [comment]
https://github.com/Polymer-Japan/polymer-jp.org/releases/tag/v0.1.0
